### ISSUE TITLE
Font is kinda blocky

### ISSUE THREAD

**Issue by BenBE** [git-learning-game/git-hydra#5]
The font (especially on the right) is kinda hard to read due to the missing anti-aliasing.

![image](https://user-images.githubusercontent.com/111196/98444979-5213ef00-2115-11eb-9d99-05dcefa1690f.png)

**Comment by blinry** [comment]
Godot is set to anti-alias (and even oversample) texts. At which window width did you try the game?

I agree that the texts on the cards look pretty bad, this is because we were lazy and just scaled fonts, instead of setting proper font sizes. The commit that closes this does this a bit better, and also increases all font sizes by 15%. Do you think that's better?

Is this maybe also an issue with the font's letter spacing? We'll probably pick a different font during some visual polishing. :)

**Comment by BenBE** [comment]
The screenshot is at native resolution, i.e. 720p. Increasing the font size by a little is in any case a good step. If the kerning of the font is a major contributor to the effect is hard to tell.

**Comment by blinry** [comment]
So while Godot was set to anti-alias texts, the label objects we had in the game were not, apparently! :O After fixing that, fonts should now be *way* smoother!
