### ISSUE TITLE
Crashes on macOS High Sierra ...

### ISSUE THREAD

**Issue by gamecubate** [git-learning-game/git-hydra#9]
immediately after dropping the git commit card onto the panel above

**Comment by ciacci1234** [comment]
I have the same scenario ✔️ App starts up, but crashing when dragging `git init` card

macOS High Sierra Version 10.13.3

**Comment by ayacksmith** [comment]
Same issue on Catalina. I was able to grab this screenshot before the crash:
<img width="1904" alt="Screen Shot 2020-11-15 at 8 20 48 PM" src="https://user-images.githubusercontent.com/15854274/99203436-92601680-2780-11eb-826f-daf6a6d83a30.png">

**Comment by blinry** [comment]
Thanks for reporting this issue! :)

@ayacksmith, hehe, that screenshot made it very clear to us what was wrong: the Mac implementation of `sed` does not seem to support the `-r` option – but it turns out we don't need it here. We deleted it, and it seems to work now.

Feel free to let us know if you encounter more issues! <3

**Comment by tasmo** [comment]
Another approach can be using awk:

```shell
awk 'sub(/^\.\.\./,"")'
```
